apiVersion: v1
kind: Service
metadata:
  name: namespace-lab
  namespace: prod
  labels:
    app: namespace-lab
spec:
  selector:
    app: namespace-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
