apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-and-memory
  namespace: limit-range-demo
spec:
  limits:
    - type: pod
      default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "250m"
        memory: "128Mi"
