apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    app: nginx-service
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine3.23-perl
      ports:
        - containerPort: 80
